### ISSUE TITLE
Please add README.md

### ISSUE THREAD

**Issue by philipmjohnson** [morea-framework/morea-lintui#1]
With user guide and screenshots? The MF user community awaits instructions anxiously.

To provide screenshots, you can create:
- create a directory called "docs"
- put screenshots in there and commit
- use browser to get the URL of the raw image.
- insert into README.md as `![](<URL to screenshot>)`

**Comment by henricasanova** [comment]
Good idea.  I am still fighting with IntelliJ and github. Something's screwy…  but, yes, that's an idea.

Henri

On Sep 13, 2015, at 12:33 PM, Philip Johnson notifications@github.com wrote:

> With user guide and screenshots? The MF user community awaits instructions anxiously.
> 
> To provide screenshots, you can create:
> 
> create a directory called "docs"
> put screenshots in there and commit
> use browser to get the URL of the raw image.
> insert into README.md as ![](URL to screenshot)
> —
> Reply to this email directly or view it on GitHub.

---

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.
