### ISSUE TITLE
Error in module sort order collision detection.

### ISSUE THREAD

**Issue by cammoore** [morea-framework/morea-lintui#5]
I was creating my second module in a new Morea repository.  The first module had a sort order of 1. When I created the second module I gave it a sort order of 100.  morea-lintui had the following output:

Acquiring MOREA content...
  Acquired content from 22 MOREA .md files

Validating MOREA content...
  Type-checking...
  Checking for duplicate ids...
  Checking for dangling/invalid references...
  Error: Files ./master/src/morea/010.introduction/module-introduction.md and ./master/src/morea/020.java-environment/module-java-environment.md have identical morea_sort_order values (100)

MOREA .md files seem to have issues. Fix the above error(s) and re-run this script (which is not as lenient as jekyll,
for good reasons).

It didn't matter what value I used for the two sort orders. It kept giving me similar errors.
It looks like the issue is in MoreaContent.py : check_for_sort_order_collisions line 195. Why are we looking at i - 2 instead of i - 1?

**Comment by henricasanova** [comment]
Yep, that’s a typo!   Should be [i-1] of course.   Can’t believe that didn’t get noticed before.   committed.

Henri
